export const VISITA_COLMEIA_GET_ALL_BY_VISITA_APIARIO = 'VISITA_COLMEIA_GET_ALL_BY_VISITA_APIARIO';
export const VISITA_COLMEIA_LOADING = 'VISITA_COLMEIA_LOADING';
export const VISITA_COLMEIA_CREATE = 'VISITA_COLMEIA_CREATE'; 