import { colors } from "../../../assets";

export default {
hive: {
  width: '90%',
  height: 100,
  backgroundColor: colors.white,
  flexDirection: 'row',
  justifyContent: 'center',
  alignItems: 'center',
  margin: 10,
  marginHorizontal: 20,
  borderRadius: 15,
  alignSelf: 'center',
},
swiperBackContent: {
  flexDirection: 'row',
  alignItems: 'center',
  flex: 1,
  margin: 10,
  marginHorizontal: 21,
  justifyContent: 'space-between',
  borderRadius: 15,
},
contentText: {
  width: '50%',
  height: '100%',
  justifyContent: 'center',
  paddingLeft: 25,
},
contentArrow: {
  width: '20%',
  height: '100%',
  justifyContent: 'center',
  alignItems: 'center',
},
arrow: {
  fontSize: 30,
  color: colors.blackgrey,
},
hiveName: {
  fontSize: 13,
  fontFamily: 'Montserrat-Bold',
},
hiveDescription: {
  fontSize: 13,
  fontFamily: 'Montserrat Regular',
},
touchStyle: {
  alignItems: 'center',
  justifyContent: 'center',
},
hiveImage: {
  width: '30%',
  height: '100%',
  justifyContent: 'center',
  alignItems: 'center',
  borderBottomLeftRadius: 15,
  borderTopLeftRadius: 15,
},
image: {
  resizeMode: 'cover',
  width: '100%',
  height: '100%',
  borderBottomLeftRadius: 15,
  borderTopLeftRadius: 15,
},
leftIcon: {
  height: '100%', 
  width: '50%', 
  borderBottomLeftRadius: 15, 
  borderTopLeftRadius: 15, 
  backgroundColor: 'transparent',
  justifyContent: 'center',
  alignItems: 'flex-start',
  padding: 10,
},
leftTouch: {
  height: '100%', 
  width: '50%', 
  borderBottomLeftRadius: 15, 
  borderTopLeftRadius: 15, 
  backgroundColor: colors.blackgrey,
  justifyContent: 'center',
  alignItems: 'flex-start',
  padding: 10,
},
rightIcon: {
  height: '100%', 
  width: '50%', 
  borderBottomRightRadius: 15, 
  borderTopRightRadius: 15, 
  backgroundColor: 'transparent',
  justifyContent: 'center',
  alignItems: 'flex-end',
  padding: 8,
},
rightTouch: {
  height: '100%', 
  width: '50%', 
  borderBottomRightRadius: 15, 
  borderTopRightRadius: 15, 
  backgroundColor: colors.blackgrey,
  justifyContent: 'center',
  alignItems: 'flex-end',
  padding: 8,
},
};
