export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOADING_LOGIN = 'LOADING_LOGIN';
export const GET_INFORMATIONS_USER = "GET_INFORMATIONS_USER";

export const RESET_STATE_ON_LOGOUT = 'RESET_STATE_ON_LOGOUT';