export const GET_ALL_APIARIOS_BY_USER = "GET_ALL_APIARIOS_BY_USER";
export const GET_APIARIOS_WITH_INTERVENCOES_IN_COLMEIAS =
  "GET_APIARIOS_WITH_INTERVENCOES_IN_COLMEIAS";
export const GET_COUNT_APIARIOS_BY_APICULTOR =
  "GET_COUNT_APIARIOS_BY_APICULTOR";

export const LOADING_APIARIO = "LOADING_APIARIO";
