export const GET_ALL_APIARIOS_BY_USER_SUCCESS = "GET_ALL_APIARIOS_BY_USER_SUCCESS";
export const GET_ALL_APIARIOS_BY_USER_ERROR = "GET_ALL_APIARIOS_BY_USER_ERROR";

export const GET_APIARIOS_WITH_INTERVENCOES_IN_COLMEIAS_SUCCESS = "GET_APIARIOS_WITH_INTERVENCOES_IN_COLMEIAS_SUCCESS";
export const GET_APIARIOS_WITH_INTERVENCOES_IN_COLMEIAS_ERROR = "GET_APIARIOS_WITH_INTERVENCOES_IN_COLMEIAS_ERROR";

export const GET_COUNT_APIARIOS_BY_APICULTOR_SUCCESS = "GET_COUNT_APIARIOS_BY_APICULTOR_SUCCESS";
export const GET_COUNT_APIARIOS_BY_APICULTOR_ERROR = "GET_COUNT_APIARIOS_BY_APICULTOR_ERROR";

export const LOADING_APIARIO = "LOADING_APIARIO";
