export const INTERVENCAO_GET_ALL_BY_APICULTOR = 'INTERVENCAO_GET_ALL_BY_APICULTOR';
export const INTERVENCAO_GET_ALL_BY_APIARIO = 'INTERVENCAO_GET_ALL_BY_APIARIO';
export const INTERVENCAO_LOADING = 'INTERVENCAO_LOADING';

export const INITIATE_CONCLUIR_INTERVENCAO_APIARIO = 'INITIATE_CONCLUIR_INTERVENCAO_APIARIO';
export const CONCLUIR_INTERVENCAO_APIARIO_COMMIT = 'CONCLUIR_INTERVENCAO_APIARIO_COMMIT';
export const CONCLUIR_INTERVENCAO_APIARIO_ROLLBACK = 'CONCLUIR_INTERVENCAO_APIARIO_ROLLBACK';

export const INITIATE_CONCLUIR_INTERVENCAO_COLMEIA = 'INITIATE_CONCLUIR_INTERVENCAO_COLMEIA';
export const CONCLUIR_INTERVENCAO_COLMEIA_COMMIT = 'CONCLUIR_INTERVENCAO_COLMEIA_COMMIT';
export const CONCLUIR_INTERVENCAO_COLMEIA_ROLLBACK = 'CONCLUIR_INTERVENCAO_COLMEIA_ROLLBACK';

export const UPDATE_COUNT_INTERVENCOES_BY_APICULTOR = 'UPDATE_COUNT_INTERVENCOES_BY_APICULTOR';
export const UPDATE_ALL_INTERVENCOES_APIARIOS = 'UPDATE_ALL_INTERVENCOES_APIARIOS';
export const UPDATE_ALL_INTERVENCOES_COLMEIAS = 'UPDATE_ALL_INTERVENCOES_COLMEIAS';