export const INTERVENCAO_GET_ALL_BY_APICULTOR = 'INTERVENCAO_GET_ALL_BY_APICULTOR';
export const INTERVENCAO_LOADING = 'INTERVENCAO_LOADING';
export const INTERVENCAO_CONCLUIR_SUCCESS = 'INTERVENCAO_CONCLUIR_SUCCESS';
export const INTERVENCAO_CONCLUIR_ERROR = 'INTERVENCAO_CONCLUIR_ERROR';

export const INTERVENCAO_GET_ALL_BY_APIARIO = 'INTERVENCAO_GET_ALL_BY_APIARIO';
export const INTERVENCAO_COLMEIA_CONCLUIR_SUCCESS = 'INTERVENCAO_COLMEIA_CONCLUIR_SUCCESS';
export const INTERVENCAO_COLMEIA_CONCLUIR_ERROR = 'INTERVENCAO_COLMEIA_CONCLUIR_ERROR';

export const GET_COUNT_INTERVENCOES_BY_APICULTOR = 'GET_COUNT_INTERVENCOES_BY_APICULTOR';
