export const INTERVENCAO_GET_ALL_BY_APICULTOR = 'INTERVENCAO_GET_ALL_BY_APICULTOR';
export const INTERVENCAO_LOADING = 'INTERVENCAO_LOADING';
export const INTERVENCAO_CONCLUIR = 'INTERVENCAO_CONCLUIR';

