export const GET_VISITAS_BY_APIARIO_URL = 'GET_VISITAS_BY_APIARIO_URL';

export const VISITA_LOADING = 'VISITA_LOADING';

export const VISITA_APIARIO_CREATE_SUCCESS = 'VISITA_APIARIO_CREATE_SUCCESS';

export const VISITA_APIARIO_DELETE_SUCCESS = 'VISITA_APIARIO_DELETE_SUCCESS';

export const INITIATE_CREATE_VISITA = 'INITIATE_CREATE_VISITA';

export const CREATE_VISITA_COMMIT = 'CREATE_VISITA_COMMIT';

export const CREATE_VISITA_ROLLBACK = 'CREATE_VISITA_ROLLBACK';