export const GET_VISITAS_BY_APIARIO = 'GET_VISITAS_BY_APIARIO';

export const VISITA_LOADING = 'VISITA_LOADING';

export const VISITA_APIARIO_CREATE_SUCCESS = 'VISITA_APIARIO_CREATE_SUCCESS';

export const VISITA_APIARIO_DELETE_SUCCESS = 'VISITA_APIARIO_DELETE_SUCCESS'; 