export const DELETE_COLMEIA = "DELETE_COLMEIA";
export const EDIT_COLMEIA = "EDIT_COLMEIA";

export const LOADING_COLMEIA = 'LOADING_COLMEIA';

export const GET_COLMEIA_BY_APIARIO = 'GET_COLMEIA_BY_APIARIO';

export const UPDATE_COUNT_COLMEIAS_BY_APICULTOR = 'UPDATE_COUNT_COLMEIAS_BY_APICULTOR';
export const UPDATE_ALL_COLMEIAS = 'UPDATE_ALL_COLMEIAS';

export const INITIATE_CREATE_COLMEIA = 'INITIATE_CREATE_COLMEIA';
export const CREATE_COLMEIA_COMMIT = 'CREATE_COLMEIA_COMMIT';
export const CREATE_COLMEIA_ROLLBACK = 'CREATE_COLMEIA_ROLLBACK';