export const DELETE_COLMEIA = "DELETE_COLMEIA";
export const CREATE_COLMEIA = "CREATE_COLMEIA";
export const EDIT_COLMEIA = "EDIT_COLMEIA";
export const LOADING_COLMEIA = 'LOADING_COLMEIA';
export const GET_COLMEIA_BY_APIARIO = 'GET_COLMEIA_BY_APIARIO';
