export const INTERVENCAO_COLMEIA_GET_ALL_BY_INTERVENCAO = 'INTERVENCAO_COLMEIA_GET_ALL_BY_INTERVENCAO';
export const INTERVENCAO_COLMEIA_LOADING = 'INTERVENCAO_COLMEIA_LOADING';
export const INTERVENCAO_COLMEIA_CONCLUIR = 'INTERVENCAO_COLMEIA_CONCLUIR';

