export const VISITA_APIARIO_GET_ALL_BY_APIARIO = 'VISITA_APIARIO_GET_ALL_BY_APIARIO';
export const VISITA_APIARIO_LOADING = 'VISITA_APIARIO_LOADING';
export const VISITA_APIARIO_CREATE = 'VISITA_APIARIO_CREATE';
export const VISITA_APIARIO_DELETE = 'VISITA_APIARIO_DELETE'; 